apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ["echo", "job-test"] 
      restartPolicy: Never
